# Base de datos (usa variables de entorno de Docker)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/app_dev}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:app_dev}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:app_dev_pwd}

# Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never


storage.s3.endpoint=http://minio:9000
storage.s3.bucket=chef-planner
storage.s3.access-key=minioadmin
storage.s3.secret-key=minioadmin
storage.s3.region=us-east-1
storage.type=s3

# Logging
logging.level.org.springframework.security=TRACE
logging.level.org.hibernate.SQL=DEBUG